# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
