# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.CharField(max_length=30),
        ),
    ]
