# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200131_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='images_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
