# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_images_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
        migrations.RemoveField(
            model_name='images',
            name='images_image',
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ManyToManyField(to='gallery.tags'),
        ),
    ]
