# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-01 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_images_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='images',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
